### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by colin314** [JacekPrzemieniecki/UNIFAC#1]
I really like your code and want to use it, but it doesn't have a license, so I am not legally able to. 

From the github docs:

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

I would be grateful if you added a license to your project so I can use it. I would recommend the MIT license if you don't really care what people do with your code.

Here are some resources:
https://docs.github.com/en/enterprise/2.15/user/articles/licensing-a-repository (github docs on licenses)
https://choosealicense.com/ (to help you choose a license)
https://choosealicense.com/licenses/mit/ (MIT license)

**Comment by JacekPrzemieniecki** [comment]
Added the MIT license
